// Mocks generated by Mockito 5.4.6 from annotations
// in causeries_client/test/features/guilds/presentation/viewmodels/channel_messages_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:causeries_client/core/network/realtime_connection.dart' as _i9;
import 'package:causeries_client/features/authentication/domain/entities/user.dart'
    as _i4;
import 'package:causeries_client/features/authentication/domain/repositories/auth_repository.dart'
    as _i8;
import 'package:causeries_client/features/guilds/domain/entities/channel.dart'
    as _i2;
import 'package:causeries_client/features/guilds/domain/repositories/channels_repository.dart'
    as _i5;
import 'package:causeries_client/features/users/domain/entities/public_user.dart'
    as _i3;
import 'package:causeries_client/features/users/domain/repositories/users_repository.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChannel_0 extends _i1.SmartFake implements _i2.Channel {
  _FakeChannel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePublicUser_1 extends _i1.SmartFake implements _i3.PublicUser {
  _FakePublicUser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_2 extends _i1.SmartFake implements _i4.User {
  _FakeUser_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChannelsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelsRepository extends _i1.Mock
    implements _i5.ChannelsRepository {
  @override
  _i6.Future<_i2.Channel> createChannel({
    required String? name,
    required String? description,
    required String? guildId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChannel, [], {
              #name: name,
              #description: description,
              #guildId: guildId,
            }),
            returnValue: _i6.Future<_i2.Channel>.value(
              _FakeChannel_0(
                this,
                Invocation.method(#createChannel, [], {
                  #name: name,
                  #description: description,
                  #guildId: guildId,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Channel>.value(
              _FakeChannel_0(
                this,
                Invocation.method(#createChannel, [], {
                  #name: name,
                  #description: description,
                  #guildId: guildId,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.Channel>);

  @override
  _i6.Future<void> deleteChannel(String? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChannel, [channelId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendMessage({
    required String? channelId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #channelId: channelId,
              #content: content,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> sendMessageRaw({
    required String? channelId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessageRaw, [], {
              #channelId: channelId,
              #content: content,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> listMessages(String? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#listMessages, [channelId]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [UsersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersRepository extends _i1.Mock implements _i7.UsersRepository {
  @override
  _i6.Future<_i3.PublicUser> getUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [id]),
            returnValue: _i6.Future<_i3.PublicUser>.value(
              _FakePublicUser_1(this, Invocation.method(#getUser, [id])),
            ),
            returnValueForMissingStub: _i6.Future<_i3.PublicUser>.value(
              _FakePublicUser_1(this, Invocation.method(#getUser, [id])),
            ),
          )
          as _i6.Future<_i3.PublicUser>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i8.AuthRepository {
  @override
  _i6.Future<_i4.User> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i6.Future<_i4.User>.value(
              _FakeUser_2(this, Invocation.method(#login, [email, password])),
            ),
            returnValueForMissingStub: _i6.Future<_i4.User>.value(
              _FakeUser_2(this, Invocation.method(#login, [email, password])),
            ),
          )
          as _i6.Future<_i4.User>);

  @override
  _i6.Future<void> register(
    String? email,
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, username, password]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i6.Future<_i4.User?>.value(),
            returnValueForMissingStub: _i6.Future<_i4.User?>.value(),
          )
          as _i6.Future<_i4.User?>);
}

/// A class which mocks [RealtimeConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeConnection extends _i1.Mock
    implements _i9.RealtimeConnection {
  @override
  _i6.Stream<Map<String, dynamic>> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<Map<String, dynamic>>.empty(),
            returnValueForMissingStub: _i6.Stream<Map<String, dynamic>>.empty(),
          )
          as _i6.Stream<Map<String, dynamic>>);

  @override
  _i6.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
