// Mocks generated by Mockito 5.4.6 from annotations
// in causeries_client/test/features/authentication/auth_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:causeries_client/core/network/api_client.dart' as _i4;
import 'package:causeries_client/core/storage/token_storage.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTokenStorage_1 extends _i1.SmartFake implements _i3.TokenStorage {
  _FakeTokenStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  @override
  _i2.Client get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeClient_0(this, Invocation.getter(#httpClient)),
            returnValueForMissingStub: _FakeClient_0(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i2.Client);

  @override
  _i3.TokenStorage get tokenStorage =>
      (super.noSuchMethod(
            Invocation.getter(#tokenStorage),
            returnValue: _FakeTokenStorage_1(
              this,
              Invocation.getter(#tokenStorage),
            ),
            returnValueForMissingStub: _FakeTokenStorage_1(
              this,
              Invocation.getter(#tokenStorage),
            ),
          )
          as _i3.TokenStorage);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i6.Future<Map<String, dynamic>> get(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#get, [path]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> post(
    String? path, {
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [path], {#body: body}),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> put(
    String? path, {
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path], {#body: body}),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> delete(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
