// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7tVQRiJPk9KHdQduTwz_-ZGrqrIT2_EA',
    appId: '1:964711021125:web:62e0bf88b971a583a7c12c',
    messagingSenderId: '964711021125',
    projectId: 'causeries-f0db0',
    authDomain: 'causeries-f0db0.firebaseapp.com',
    storageBucket: 'causeries-f0db0.firebasestorage.app',
    measurementId: 'G-DQ71P8MSY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ0pST4487TOsQ-TtEt11gMoDNpyaZn-A',
    appId: '1:964711021125:android:43d70e508164c099a7c12c',
    messagingSenderId: '964711021125',
    projectId: 'causeries-f0db0',
    storageBucket: 'causeries-f0db0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzYCWKJ6KVXHhQpZ3h3cMakoePhy6kxC0',
    appId: '1:964711021125:ios:2da10783c0e20808a7c12c',
    messagingSenderId: '964711021125',
    projectId: 'causeries-f0db0',
    storageBucket: 'causeries-f0db0.firebasestorage.app',
    iosBundleId: 'com.causeries.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzYCWKJ6KVXHhQpZ3h3cMakoePhy6kxC0',
    appId: '1:964711021125:ios:2da10783c0e20808a7c12c',
    messagingSenderId: '964711021125',
    projectId: 'causeries-f0db0',
    storageBucket: 'causeries-f0db0.firebasestorage.app',
    iosBundleId: 'com.causeries.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7tVQRiJPk9KHdQduTwz_-ZGrqrIT2_EA',
    appId: '1:964711021125:web:8613a3f7c932f8a5a7c12c',
    messagingSenderId: '964711021125',
    projectId: 'causeries-f0db0',
    authDomain: 'causeries-f0db0.firebaseapp.com',
    storageBucket: 'causeries-f0db0.firebasestorage.app',
    measurementId: 'G-TWS0C6XHJ1',
  );
}
